name: Set up zb
description: Install zb
author: The zb Authors
inputs:
  zb-version:
    description: The zb version to download and use. Be sure to enclose this option in single quotation marks.
  zb-serve:
    description: Whether to start `zb serve`.
    default: "true"
  configuration:
    description: Additional configuration to use as a string in JSON With Commas and Comments format.
  server-download-discovery:
    description: Binary cache discovery document for downloading.
  server-upload-discovery:
    description: Binary cache discovery document for uploading.
  signing-key:
    description: Signing key as a string in JSON format. Typically stored as a secret.
  use-root:
    description: Whether to run the installer and `zb serve` as root.
    default: "true"
  github-token:
    description: Personal access token (PAT) used to get zb release information.
    default: ${{ github.token }}
runs:
  using: node24
  main: dist/main.js
  post: dist/post.js
